# Generated by Django 4.0.2 on 2022-02-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='this is name of manager', max_length=150, verbose_name='Name of manager')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
