# Generated by Django 4.0.2 on 2022-02-23 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='i',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
