# Generated by Django 4.0.2 on 2022-02-23 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_product_i'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=None, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='i',
        ),
    ]
