# Generated by Django 4.0.2 on 2022-02-23 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_image_remove_product_i'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
